### PR TITLE
Create GOES-16.json

### PR DESCRIPTION
**Pull request by zeke800**
Just working on some GOES-16 :)

Not sure if it works... but all the info seems to be correct.

### CODE REVIEW

**Comment by sgcderek** [comment]
Would you happen to have a baseband recording of the 1693 MHz downlink, and at least a screenshot of the FFT of the raw data link, so that the bandwidth can be correctly estimated?

**Comment by zeke800** [comment]
Yes, I have a few old recordings lying around here and there from when my SNR was not very good (I don't have a 24/7 station for GOES, so I receive it only sometimes). The signal seems to fit quite nicely within a 50KHz bandwidth, so I will update it right now. 
image

Thank you for replying!

**Comment by zeke800** [comment]
Well, I actually guessed it right on the first try 😎 !! No need for changes. Also, I created a GOES-17 file too.

**Comment by zeke800** [comment]
Fixed up the build. As it turned out, 0000 is not a valid integer 👍 

Thank you for accepting the images, by the way!!

**Comment by zeke800** [comment]
I just ran a "local" copy of satfreq, and can confirm it works. 
image

**Comment by zeke800** [comment]
I am also trying to add a "Decoders and other useful links" section, do you think that is a good idea?

**Comment by zeke800** [comment]
AAAAHAHHH I'm doing too many things... added a proper bookmark download page. Still a bit crooked in some places (I'm no good at HTML), but looks ok. 
image

**Comment by sgcderek** [comment]
> I am also trying to add a "Decoders and other useful links" section, do you think that is a good idea?

That is beyond the scope of this project, the current goal is to only list the bare minimum factually verifiable information, i.e. the physical properties of the signal.

Also, could you please share the baseband recording of the GOES 1693 MHz downlink so its symbol rate and modulation can be verified? Or a link to the official documentation containing the relevant information

**Comment by Xerbo** [comment]
> AAAAHAHHH I'm doing too many things... added a proper bookmark download page. Still a bit crooked in some places (I'm no good at HTML), but looks ok.

This is outside the scope of this PR, revert the last commit and open a new PR. Also include logos in the repository (preferably as SVGs)

**Comment by zeke800** [comment]
> Also, could you please share the baseband recording of the GOES 1693 MHz downlink so its symbol rate and modulation can be verified? Or a link to the official documentation containing the relevant information.

There was a project from OSP called "tlmdemod". This is a screenshot of their GNURadio demodulator. 
image

The baud rate is set to 40k, and the signal is BPSK (I think with convolutional codes?). I will share a recording shortly. 


> This is outside the scope of this PR, revert the last commit and open a new PR. Also include logos in the repository (preferably as SVGs)

Thank you for the notice, I shall do that shortly 😉

**Comment by zeke800** [comment]
I have recorded a small bit of data which came through GOES-16 at 20:49UTC today. If you need to satisfy your curiosity by decoding an entire HRIT image dump, I'll send a longer recording 😉

image
[baseband_1693655100Hz_16-57-32_27-07-2022.zip]

Download the baseband here:
(https://github.com/sgcderek/satfreq/files/9203541/baseband_1693655100Hz_16-57-32_27-07-2022.zip)

**Comment by zeke800** [comment]
I got rid of the download page.

**Comment by zeke800** [comment]
Also, @sgcderek can you please send your flowgraph on analyzing these signals? Thank you :)

**Comment by sgcderek** [comment]
> Also, @sgcderek can you please send your flowgraph on analyzing these signals? Thank you :)

it is now in [here](https://github.com/sgcderek/flowcharts)

**Pull request merged**
